site_name: LocationDB
site_description: Location Database
site_url: https://location-db.pages.dev
theme:
  name: readthedocs
  highlightjs: true

nav:
  - Home: index.md
  - Using the API: api.md
  - Contribute: contribute.md